# Generated by Django 3.2.3 on 2024-09-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20240920_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='short_link',
            field=models.CharField(default='x97JTY6cFZDD', max_length=6, verbose_name='Короткая ссылка'),
        ),
    ]
