# Generated by Django 3.2.3 on 2024-09-21 11:20

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_recipe_short_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='short_link',
            field=models.CharField(default=core.utils.generate_short_link, max_length=6, verbose_name='Короткая ссылка'),
        ),
    ]
