# Generated by Django 3.2.3 on 2024-10-10 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_shoppingcart_unique_author_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Избранный рецепт',
                'verbose_name_plural': 'Избранные рецепты',
                'db_table': 'cookbook_recipe_favorite',
                'default_related_name': 'recipe_favorite',
            },
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='unique_author_recipe',
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('author', 'recipe'), name='unique_shopping_cart'),
        ),
        migrations.AddField(
            model_name='recipefavorite',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_favorite', to=settings.AUTH_USER_MODEL, verbose_name='Владелец корзины покупок'),
        ),
        migrations.AddField(
            model_name='recipefavorite',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_favorite', to='api.recipe', verbose_name='Рецепт'),
        ),
        migrations.AddConstraint(
            model_name='recipefavorite',
            constraint=models.UniqueConstraint(fields=('author', 'recipe'), name='unique_recipe_favorite'),
        ),
    ]
